---
title: "counties"
output: rmarkdown::html_vignette
bibliography: US_boundaries.bib
vignette: >
  %\VignetteIndexEntry{counties}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

From the Census Website (@bureau_substantial_nodate): 

> Substantial county boundary changes are those affecting an estimated population of 200 or more; 
> changes of at least one square mile where an estimated population number was not available, 
> but research indicated that 200 or more people may have been affected; 
> and annexations of unpopulated territory of at least 10 square miles 

Hence they are two conditions to motivate change in county boundary: 

  - change affectiing an estimated population of 200 or more
  
  - change affecting unpopulated territory of at least 10 square miles

If changes exist but do not match one of those conditions they will not be implemented. 

The US census is providing a list of change starting in 1970 and update it every decade. 

## 1960

It is unclear how were the county in the 60'. 
We can check this [file](https://www2.census.gov/programs-surveys/metro-micro/geographies/reference-files/1960/historical-delineation-files/60mfips.txt)

## 1970

States with changes: 

- Alaska

- South Dakota

- Virginia ([independent city](https://en.wikipedia.org/wiki/Independent_city_(United_States)))

## 1980

States with changes:

- Alabama

- Alaska

- Arizona

- Colorado

- Georgia

- Illinois

- Mississippi

- Missouri

- North Dakota

- Tennessee

- Texas 

- Virginia

## 1990 

### States with changes:

- Alaska

- Indiana

- Florida

- Maryland

- Montana

- North Carolina

- New Mexico

- Pennsylvania

- Puerto Rico

- Virginia

### Data and software:

The older boundaries it seems we can get from Census is 1992.
They can be find here: https://www2.census.gov/geo/tiger/TIGER1992/ and are in the original TIGER/LINE format (GDAL has driver for it). Sadly some works need to be done to convert those LINEs into a merged polygones for census county boundary. GDAL used to come with `tigerpoly.py` for that (see: https://gdal.org/en/latest/api/python_samples.html#python-samples).  

> The TIGER/Line coordinate system is hardcoded to NAD83 lat/long degrees.


## 2000

### States with changes:

- Alaska

- Colorado

- Illinois

- New Mexico

- Virginia

## 2010 

### States with changes:

- Alaska

- Louisiana

- South Dakota

- Virginia

## 2020

### States with changes: 

- Connecticut 

Connecticut's Councils of Governments (COGs) are County Equivalent Entities (See [link](https://www2.census.gov/geo/pdfs/reference/ct_county_equiv_change.pdf)).

The notice of the Census bureau (@noauthor_change_2022) is a good read and go bit deeper on it (not only counties but also National standard county code)

On the ACS side the [ACS 5-years]( https://acsdatacommunity.prb.org/discussion-forum/f/forum/1266/new-connecticut-counties-er-regions) (2022) and now ACS 1 year will use the nine COGs.

## Summary:

So far the options are:

- a county has been fully incorporated in an other one 
- a county has been partially incorporated in multiple?

The US Census utilize this way to describe those changes: 

- Changes to counties or County Equivalent Entities

- Deleted counties or County Equivalent Entities

- New Counties or County Equivalent Entities

- Substantial County or County Equivalent Entity Boundary Changes

- Name and/or Code Changes or Corrections for Counties or County Equivalent Entities (Ex LaSalle -> La Salle)

## References
